[package]
name = "re_v_ult"
version = "0.1.0"
edition = "2021"

[dependencies]
funty = "2.0.0"
bitvec = "1"

[dev-dependencies]
rusty-hook = "^0.11.2"

[dependencies.sdl2]
version = "0.37.0"
default-features = false
features = ["gfx"]